eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: gateway

  cloud:
    gateway:
      default-filters:
        - RemoveRequestHeader=Cookie
        - RemoveResponseHeader=X-Powered-By

      routes:

        # ===================== Participant Service =====================
        - id: participant-players
          uri: http://participant-service:8081
          predicates:
            - Path=/api/participant/players/**,/api/participant/players/public/**
          filters:
            - name: JwtGatewayFilter

        - id: participant-teams
          uri: http://participant-service:8081
          predicates:
            - Path=/api/participant/teams/**,/api/participant/teams/public/**
          filters:
            - name: JwtGatewayFilter

        - id: participant-orgs
          uri: http://participant-service:8081
          predicates:
            - Path=/api/participant/organizations/**,/api/participant/organizations/public/**
          filters:
            - name: JwtGatewayFilter

        # ===================== Match Service =====================
        - id: match-service
          uri: http://match-service:8082
          predicates:
            - Path=/api/matches/**,/api/matches/public/**,/api/matches/private/**,/api/matches/player/**,/api/matches/organizer/**
          filters:
            - name: JwtGatewayFilter

        # ===================== Tournament Service =====================
        - id: tournament-service
          uri: http://tournament-service:8083
          predicates:
            - Path=/api/tournaments/**,/api/tournaments/public/**,/api/tournaments/private/**,/api/tournaments/player/**,/api/tournaments/organizer/**,/api/tournaments/moderator/**
          filters:
            - name: JwtGatewayFilter

        # ===================== Auth Service =====================
        - id: auth-service
          uri: http://auth-service:8084
          predicates:
            - Path=/auth/**,/api/auth/public/**
          filters:
            - name: JwtGatewayFilter

        # ===================== Game Service =====================
        - id: game-service
          uri: http://game-service:8085
          predicates:
            - Path=/api/game/**,/api/game/public/**,/api/game/private/**
          filters:
            - name: JwtGatewayFilter

server:
  port: 8777