eureka:
  client:
    service-url:
      defaultZone: http://discovery:8761/eureka

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://host.docker.internal:5432/Tournament_org}
  redis:
    host: ${SPRING_REDIS_HOST:host.docker.internal}
    port: ${SPRING_REDIS_PORT:6379}
    password: ${SPRING_REDIS_PASSWORD:}
    database: ${SPRING_REDIS_DATABASE:0}
